### ISSUE TITLE
1.5.0-9 crafting alter missing texture after constructed

### ISSUE THREAD

**Issue by alpha8196** [Growlith1223/ArsMagica2#71]
as title
[http://imgur.com/Dnzv7fr](url)

**Comment by Growlith1223** [comment]
your image links are broken

**Comment by alpha8196** [comment]
[http://i.imgur.com/Dnzv7fr.png](url)

**Comment by alpha8196** [comment]
not sure why but it seems if you copy and pate the link to the browser and it'll work

**Comment by Growlith1223** [comment]
that is super weird with that, anywho, i'll take a look at it, thanks for letting me know!

**Comment by Growlith1223** [comment]
ok, so, im unable to reproduce this lol, i /might/ have fixed it after i released 1.5.0-9, im not sure, im going to leave this open until the next version(which is in a few hours), so if it persists in that version as well, just say something here

**Comment by alpha8196** [comment]
its still there

**Comment by Growlith1223** [comment]
i seriously don't see how, im looking at a crafting altar right now and it looks perfectly fine

**Comment by alpha8196** [comment]
it might have something to do with the other mods I have…I'll start checking when I get back to my dorm

**Comment by alpha8196** [comment]
@Growlith1223 I made a new instance with the newest version of forge(1.10.2-12.18.3.2185) , Ars Magica 2 (1.5.0-11) and nothing else,still missing texture

**Comment by Growlith1223** [comment]
ahh, you're running 2185 lol, the mod was made in 2125, gimme a few mins to update the dev environment

**Comment by alpha8196** [comment]
lesson learned : always include forge version in a bug report
should I add this information to my other bug reports?

**Comment by Growlith1223** [comment]
would probably be a good idea. i was sitting here, reinstalling version 2125 over and over trying to see why you're getting the missing texture only to find out, you're on an entirely different version XD

**Comment by alpha8196** [comment]
yeah that totally sucks ,sry bro.

**Comment by Growlith1223** [comment]
lol you're fine, i just didn't even think about forge versions

**Comment by Growlith1223** [comment]
ok this is very weird, i am running on 2185 now as well, i get the texture perfectly fine lol

http://prntscr.com/dgk03n

**Comment by alpha8196** [comment]
@Growlith1223 so apparently this will only happen when the alter is opened on the north-south sides
[http://imgur.com/fUYgZpK](url)

**Comment by Growlith1223** [comment]
http://prntscr.com/dgknxv lol, by chance are on an AMD graphics card?

**Comment by alpha8196** [comment]
now this is getting weird...
and no,I'm on GTX970M

**Comment by Growlith1223** [comment]
im on nvidia as well, wtf

**Comment by Growlith1223** [comment]
and there's absolutely nothing else added? no optifine, betterFPS, etc?

**Comment by alpha8196** [comment]
nope just AM2

**Comment by Growlith1223** [comment]
i legit do not know why it's working for me but not for you lol

is there anything in the logs about the crafting altar?

**Comment by alpha8196** [comment]
no,I cant even find the word altar in the logs

this is the weirdest situation I've been in Minecraft ,lol

**Comment by Growlith1223** [comment]
yea this is super weird, does it happen on every single structure material you can use as well or is it just the witchwood?

**Comment by alpha8196** [comment]
switched to birch and redstone block same issue

**Comment by Growlith1223** [comment]
then wtf, why does that happen!?

your graphics card isn't an old one, it's relatively new, so drivers wouldn't be the issue here(i don't think at least)

**Comment by alpha8196** [comment]
in case you might ask,i am on the newest version of java (Version 8 Update 111)

**Comment by Growlith1223** [comment]
i am as well, i am vexed by the complexity of this god forsaken issue lmao

**Comment by alpha8196** [comment]
aye,Such little issue but with such great complexity,

I can probably make a meme out of this

**Comment by Orinion** [comment]
i was able to reproduce this bug in 1.5.0-15 with Forge 12.18.3.2185
with an AMD Radeon R9
http://imgur.com/a/Rm5yi

**Comment by EPIICTHUNDERCAT** [comment]
interesting good to know @Growlith1223 seems to still be around, ill be testing this later.

**Comment by TheIcyOne** [comment]
Might be a Windows only issue, since you mentioned that you are using Linux.

**Comment by Not-February** [comment]
I'm on a Mac and am getting this as well, with 1.5.0-17 and Forge 12.18.3.2221. Tried both acacia planks and jungle planks.

I'm going to uninstall all of my other mods and test to see if it persists.

EDIT:

Well, with absolutely nothing but Forge and AM2 installed, I'm still getting this.

http://i.imgur.com/ERfxNV4.png

The orientation of the crafting altar structure seems to be a factor.

**Comment by TheIcyOne** [comment]
Looks like the north-south orientation works correctly, and the east-west orientation is the broken one.

**Comment by Growlith1223** [comment]
fixed! this was stupid lol

**Comment by TheIcyOne** [comment]
[20:03] <Growlith1223> that was quite possibly one of the most derpiest things i've ever seen in regards to bugs

I consider this official enough certification.
